use anyhow::Result;
use sqlx::sqlite::SqlitePool;
use sqlx::{Row as SqlxRow, Column as SqlxColumn};

// Reads any SQLite database file and returns human-readable output
pub async fn read_database(path: &str) -> Result<String> {
    let conn_str = format!("sqlite:{}?mode=ro", path);
    let pool = SqlitePool::connect(&conn_str).await?;

    let mut output = String::new();
    output.push_str(&format!("Database: {}\n", path));
    output.push_str(&format!("{}\n\n", "-".repeat(40)));

    // Get all tables
    let tables: Vec<String> = sqlx::query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
        .fetch_all(&pool)
        .await?
        .iter()
        .map(|row| row.get::<String, _>("name"))
        .collect();

    if tables.is_empty() {
        output.push_str("(empty database)\n");
        return Ok(output);
    }

    output.push_str(&format!("Tables: {}\n\n", tables.join(", ")));

    for table in &tables {
        output.push_str(&format!("table {} {{\n", table));

        // Get column info
        let pragma = format!("PRAGMA table_info({})", table);
        let columns = sqlx::query(&pragma).fetch_all(&pool).await?;

        for col in &columns {
            let name: String = col.get("name");
            let col_type: String = col.get("type");
            let notnull: i32 = col.get("notnull");
            let dflt: Option<String> = col.try_get("dflt_value").ok();

            let kairo_type = match col_type.to_uppercase().as_str() {
                "TEXT" | "VARCHAR" | "CHAR" => "string",
                "INTEGER" | "INT" | "BIGINT" | "SMALLINT" => "int",
                "BOOLEAN" | "BOOL" => "bool",
                "REAL" | "FLOAT" | "DOUBLE" => "float",
                "BLOB" => "blob",
                _ => "string",
            };

            let mut line = format!("  {}: {}", name, kairo_type);
            if let Some(ref default) = dflt {
                if !default.is_empty() {
                    line.push_str(&format!(" = {}", default));
                }
            }
            if notnull == 1 {
                line.push_str(" [required]");
            }
            output.push_str(&format!("{}\n", line));
        }

        output.push_str("}\n\n");

        // Show row count and sample data
        let count_query = format!("SELECT COUNT(*) as cnt FROM {}", table);
        let count_row = sqlx::query(&count_query).fetch_one(&pool).await?;
        let count: i32 = count_row.get("cnt");
        output.push_str(&format!("  -- {} rows\n", count));

        if count > 0 {
            let sample_query = format!("SELECT * FROM {} LIMIT 5", table);
            let rows = sqlx::query(&sample_query).fetch_all(&pool).await?;

            for row in &rows {
                let mut fields = Vec::new();
                for col in row.columns() {
                    let name = col.name();
                    let value: String = row.try_get(col.ordinal()).unwrap_or_else(|_| "null".to_string());
                    fields.push(format!("{}: {}", name, value));
                }
                output.push_str(&format!("  | {}\n", fields.join(" | ")));
            }
            if count > 5 {
                output.push_str(&format!("  ... and {} more rows\n", count - 5));
            }
        }
        output.push('\n');
    }

    pool.close().await;
    Ok(output)
}

// Export a database to .kairo schema files
pub async fn export_schema(path: &str) -> Result<String> {
    let conn_str = format!("sqlite:{}?mode=ro", path);
    let pool = SqlitePool::connect(&conn_str).await?;

    let mut output = String::new();
    output.push_str("// Generated by KairoDB\n");
    output.push_str(&format!("// Source: {}\n\n", path));

    let tables: Vec<String> = sqlx::query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
        .fetch_all(&pool)
        .await?
        .iter()
        .map(|row| row.get::<String, _>("name"))
        .collect();

    for table in &tables {
        output.push_str(&format!("table {} {{\n", table));

        let pragma = format!("PRAGMA table_info({})", table);
        let columns = sqlx::query(&pragma).fetch_all(&pool).await?;

        for col in &columns {
            let name: String = col.get("name");
            let col_type: String = col.get("type");
            let dflt: Option<String> = col.try_get("dflt_value").ok();

            let kairo_type = match col_type.to_uppercase().as_str() {
                "TEXT" | "VARCHAR" | "CHAR" => "string",
                "INTEGER" | "INT" | "BIGINT" | "SMALLINT" => "int",
                "BOOLEAN" | "BOOL" => "bool",
                "REAL" | "FLOAT" | "DOUBLE" => "float",
                "BLOB" => "blob",
                _ => "string",
            };

            let mut line = format!("  {}: {}", name, kairo_type);
            if let Some(ref default) = dflt {
                if !default.is_empty() {
                    line.push_str(&format!(" = {}", default));
                }
            }
            output.push_str(&format!("{}\n", line));
        }

        output.push_str("}\n\n");
    }

    pool.close().await;
    Ok(output)
}
